### PR TITLE
Fix for qr scanner on chrome, safari and mobile

### PR DESCRIPTION
**Pull request by seanjparker**
For issue #64 

I have updated instascan to the latest version with some adjustments to make it work on safari and iOS. It should work more universally, but we should test it on multiple devices just in case.

Better not to merge it yet until more manual tests have been performed.

### CODE REVIEW

**Review by kzalys — CHANGES_REQUESTED** [review]
It still does not work on Chrome on iOS and Android and it uses the front facing camera on Safari on iOS. Seems to be working alright on Chrome on Windows

**Comment by seanjparker** [comment]
> It still does not work on Chrome on iOS and Android and it uses the front facing camera on Safari on iOS. Seems to be working alright on Chrome on Windows

Unfortunately, we can't use the camera in Chrome for iOS as WebRTC (the way instascan accesses the cameras) isn't supported in Chrome.

**Comment by kzalys** [comment]
While it not working on iOS Chrome might be too big of a problem, it has to work on Android Chrome.

I found this scanner https://webqr.com/ which seems to work well on all my devices except for Firefox and Edge on Windows but our current solution doesn't work on these browsers either.
It uses this library: https://github.com/LazarSoft/jsqrcode

Might be worth checking it out.

Bottom line is we can't rely on the QR scanner on the hub and we'll need to adapt other parts of the hub to be usable through 3rd party scanners.

**Comment by kzalys** [comment]
I don't think hard coding the camera choice is a good solution. What could work is just picking the first camera at the start and adding a button that cycles through the available cameras.
Then we could save the user's choice in cookies and use this setting the next time we load the scanner.

**Comment by seanjparker** [comment]
> I don't think hard coding the camera choice is a good solution. What could work is just picking the first camera at the start and adding a button that cycles through the available cameras.
> Then we could save the user's choice in cookies and use this setting the next time we load the scanner.

I agree, I was just testing to make sure I can access the rear camera. It works in Safari in iOS, but it is mirrored at the moment

**Comment by seanjparker** [comment]
With the latest commit, it no longer mirrors when using the rear-facing camera, but the front-facing camera is still mirrored (only on mobile it seems).

@kzalys can you do a test on Android please

**Comment by kzalys** [comment]
> With the latest commit, it no longer mirrors when using the rear-facing camera, but the front-facing camera is still mirrored (only on mobile it seems).
> 
> @kzalys can you do a test on Android please

The camera on Android still doesn't load up.

**Review by kzalys — APPROVED** [review]

**Pull request merged**
