### PR TITLE
Hardware library

### PR DESCRIPTION
**Pull request by seanjparker**
Pull request for #3 
Added functionality for the hardware library.
There are two new routes added:
- Reserving an item from the hardware library (accessible by all users)
- Taking and returning an item (accessible by volunteers or organizers)

Taking or returning an item is all done through the route `take`, we store the status of the reservation in the database.

### CODE REVIEW

**Review by kzalys — COMMENTED** [review]
Do we have a route to return an item?

**Review by kzalys — CHANGES_REQUESTED** [review]
Fantastic work!
One small thing though: could we have a route that returns all items in the hardware library and their stock.
It would be used when rendering the hardware library page on the front-end and does not any authorization level restrictions.

**Comment by seanjparker** [comment]
What format should the returned results be in?
Something like this:
```json
{
  "itemCount": "...",
  "items": [
    {
      "itemName": "....",
      "itemURL": "....",
      "itemStock": "....",
      "itemHasStock": "true/false"
    },
    {
      "itemName": "....",
      "itemURL": "....",
      "itemStock": "....",
      "itemHasStock": "true/false"
    }
  ]
}

**Comment by kzalys** [comment]
A simple array of all the items is fine

**Comment by seanjparker** [comment]
Added the two new methods in latest commit

**Pull request merged**
